### ISSUE TITLE
Add images + video

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#15]
"Please use the following photos.  You can delete all the ones in there now and just use these.  You can put the titile of each photo under or in it.  I want to have each photo and video linked to one of the subjects under "our services" so when they see "solar panels" under Industrial, they have a link to the photo.  Maybe the word itself can be a link. ​I may have to explain this one.   Also, If you go to the youtube link below, I have 3 videos that I would like inserted (you have 1 in there already)."

https://www.youtube.com/channel/UCIQByUqcXYYtmUJtszsMQnA

Meg, I'll forward you the email that has all the images he sent me. Please put all these images into our google drive in the correct folder and per the instructions given above, load them onto the site as well. 

due:
10-15-15   3p

**Comment by vanderbeam** [comment]
Done.

**Comment by rodneystrong** [comment]
Good job on this. 

Few things: 
Is there a way to add the title of the images underneath each image? Try and find a way if possible. There's most likely a free plugin that allows this. 

>"I like how they have “all” and then it can be broken
down into subcategories.  I would like to copy this idea if possible.  We would have 
to crop some pictures to make them fit into squares but it looks very neat and 
organized:"

http://www.newheightsphoto.com/our-projects/

Ken also mentioned he's ok with the way this site does it too:
http://aerialrealestatephotographers.com/gallery/

**Comment by rodneystrong** [comment]
Here's an update from the client: 

>I’m really not loving the photo gallery section. The photos just seemed thrown on there with no order or reason.  Maybe we can figure out a way to organize the pictures in a meaningful way.  I still want them to be linked to the Our Services section so someone can click on the service we provide and see a sample photo or video.  My primary service is taking professional photos and videos, but this page makes me look like an amateur.  

The previous comment above this still applies; Find a way to mimic what you see in the previous example sites Ken gave us.

**Comment by rodneystrong** [comment]
When he starts talking about the "Our Services" section, do you understand what he's going for? 

If not I can help clarify.

**Comment by vanderbeam** [comment]
@rodneystrong 
All the pictures already list the file name under them. Unless you mean when they're on the grid?

I can only assume he wants each of the pictures to link to the pages that the "Our Service" categories link to. So for example the picture of people canoeing would have a link to the Events and Sports page. Possibly even have the groups of pictures appearing on the page itself. So the Real Estate page would have all the pictures and videos that get categorized under real estate. Is this correct?

I also don't know what "meaningful way" he wants me to organize these pictures. I can categorize them, sure, but except for the ONE canoe picture that could possibly be a sporting event, the rest of the pictures could easily fall into either industry or real estate categories. He's going to have to give me more of hint of how he wants these organized because besides one or two hints from the titles, the best I can make of them is "grass" and "no grass." 

Based on the style of the other site, I'm going to use a different plugin I have a lot of experience with. It's not a gallery plugin but a portfolio plugin. It is super simple to use and best of it has a categories function. However, something he may or may not want to utilize, is the details feature. If you click on the details of a picture it will take you to a page that acts as a post where you can list more pictures (and videos) related to this project. So he would have the option to create entire posts with all the pictures from a specific project listed within it. If you'll notice, the New Heights' gallery has a similar function thought it displays the pictures there instead of on another page. Actually the entire plugin looks a lot like the gallery style used on the New Heights page.

IF HE DOESN'T WANT THAT, I can just manipulate the css and hide the button to go to the post so he'd old have the features gallery option.

With a little searching I'm sure I could also find a separate image gallery that utilized categories. I just wanted to throw out the portfolio style idea. 

Would love to hear your feedback.

**Comment by rodneystrong** [comment]
>Based on the style of the other site, I'm going to use a different plugin I have a lot of experience with. It's not a gallery plugin but a portfolio plugin. It is super simple to use and best of it has a categories function

YES, use that plugin please. And YES, display:none the button to go to the post. 

>I also don't know what "meaningful way" he wants me to organize these pictures. I can categorize them, sure, but except for the ONE canoe picture that could possibly be a sporting event, the rest of the pictures could easily fall into either industry or real estate categories. He's going to have to give me more of hint of how he wants these organized because besides one or two hints from the titles, the best I can make of them is "grass" and "no grass."

I imagine he wants them categorized according to "real estate" "industrial" and "events/sports" like on the home page. 

>I can only assume he wants each of the pictures to link to the pages that the "Our Service" categories link to. So for example the picture of people canoeing would have a link to the Events and Sports page. Possibly even have the groups of pictures appearing on the page itself. So the Real Estate page would have all the pictures and videos that get categorized under real estate. Is this correct?

Don't think so, I'll read this again later tonight and either offer a video explanation or type one up if I think I can be clear through text. 

You've got enough to move forward with the other two items though.

**Comment by vanderbeam** [comment]
I realize he wants "real estate" "industrial" and "events/sports," but like I said, except for the one canoe picture, the rest of the photos could easily fall into either category or industrial or real estate. For example... a lot of those pictures of dirt lots, are they suppose to represent real estate or industrial because they're of construction? A cell tower? I would assume that anything with "inspection" is industrial but the solar panel one could just as easily be real estate. Do you see where I'm coming from? 
I plan on using my best judgement and we can always reorganize it later, but I just wanted to clarify my concern. 
I'll get right on this.

**Comment by rodneystrong** [comment]
aaAAAAaaahh  yea yea i got you. thanks for clarifying. 

yes, please take the initiative and use your best judgement for now which will prompt a correction email from him.

**Comment by vanderbeam** [comment]
So there's some sort of incompatibility between the plugin I wanted to use and the theme. I'm looking for a free alternative but I would like to suggest a possibility: http://supsystic.com/plugins/photo-gallery/

This plugin had a couple free views. Unfortunately its "Categories" view is a "pro" feature; however, I find the plugin to be absolutely breathtaking. It also gives the ability to link (for example we'd link industrial pictures to the Industrial package page) on the photo. 

Anyway, it's only $30 and since I know he is concerned with the appearance of his gallery I figured it wouldn't hurt to suggest it. And like I said I am looking for a free alternative in the meantime.

**Comment by rodneystrong** [comment]
Try these possible ones: 
https://wordpress.org/plugins/nextgen-gallery/

https://wordpress.org/plugins/photo-gallery/

Try them out and by tomorrow night you don't like them, then let me know right away and I'll buy that plugin for you.

**Comment by rodneystrong** [comment]
Ok, cenpac is now good to go; got the gallery plugin fixed from support.
