### ISSUE TITLE
Pricing adjustments

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#18]
>I’ve attached a more detailed pricing sheet for the packages.  Here is how I would like it to look
- Should say “package pricing” at the top and placed in the black bar like individual pricing is.
- I like the layout of 3 photo packages on top and 3 video packages below it and centered
- Reduce the size of the headings and price and eliminate the word packages for each column.  Should be big just not as big as it is now.
-The word “Basic” “Advanced” etc. should be centered above the price and centered in the column

I've also attached his new pricing tables:
[pricing for cenpac.docx](https://github.com/EditLLC/client-cenpac/files/13694/pricing.for.cenpac.docx)

>The one thing that I can say I’m really picky about is the layout.  I like websites where the text and designs are centered and aligned properly (as much as possible).  
For example, on my site under Pricing, the “Photo Package” and “Basic Video 
Package” are level and lined up nicely.  The “Advanced Video Package” is not.  Also the text is not centered in the box but the price is.

due:
10-16-15  8p

**Comment by vanderbeam** [comment]
I made the changes he requested as far as making the headers and prices smaller and updated the pricing tables. However, he mentions everything being "level." When I hear level I think of things being aligned horizontally, which I can only assume he means the height of the tables. I think he would find a level height on these tables aesthetically displeasing. The photography tables wouldn't look SO bad with a min-height of about 410px under the ".rpt_style_basic .rpt_plan .rpt_features" classes since they have nearly the same information, but adding a same height to the video pricing table would be very unfortunately looking.

**Comment by rodneystrong** [comment]
he likes the way this looks, good job. the assumptions you made off of what you read were true.
