### ISSUE TITLE
Home page adjustments

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#19]
>Home Page (add this to my existing sentence).
Cenpac Images offers stunning aerial videos and photographs to highlight your unique vision.  We are approved by the FAA to operate unmanned aerial vehicles for commercial purposes and we carry complete liability insurance.  Our training standards go far beyond what is required and our highly rated customer service ensures you are 100% satisfied with the completed project.
- Change my wife’s title to Director of Client Services
- Add an email icon (maybe centered just above the youtube icon and below our titles) under Our Team (linked to each of our emails)

due:
10-15-15  11p

**Comment by vanderbeam** [comment]
AHHH, this was fun! I did a little bit of oakie rigging to make this work with the social icons we needed. :)
So the team members are maintained through the "our team" widget. Easy peasy, right? Well when editing team members or adding them in the future, you'll need to know: 
Facebook link = Facebook
Twitter link = YouTube
Behance link = Google+
Dribble link = mailto: 

As a utility option, would it perhaps be better to just wipe out the social icons completely since both sets link to the same pages and the exact same links are also in the footer? It seems a little redundant to have two sets of social links so close together that go to the same place. And with the gallery page, it's not like they're risking not having people see their portfolio.

Oh also, I used ken's email from the footer but I don't know his wife's (I used "laurleen@cenpacimages.com" as a placeholder, figuring it would be a close guess)

**Comment by vanderbeam** [comment]
I can't for the life of me figure out why it's off-centre though... I've swapped out some of the icons and adjusted the css with no avail. Just wanted to let you know I was aware.

**Comment by rodneystrong** [comment]
nice work dude, i know what's going on with the email icon centering.
i'll go over this with you next time you're here in person.

**Comment by rodneystrong** [comment]
Actually, im gonna close this issue to declutter the issue queue and paste the code I used here for your reference:

````
.team-member .social-icons ul>li:first-child {
        margin-left: 11px;   
}
````

I used the first-child pseudo selector to target just the first li in that ul to then center it using margins
