### ISSUE TITLE
More adjustments from client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#21]
Pricing Page:

1.  Change the top header from “package pricing” to just “pricing”

2.  On the pricing page, delete the words “package pricing” on the top left side.  Also delete the sentence “please see our plans below.”

3.  Shrink the size of the "package price" boxes a little​​​​​​​​​​ and shrink the font size of the actual price by about 1/3.

4.  Make the "commercial fee..." line under each each package about 2 font sizes smaller (if it's still readable)  

5.  Add this sentence below the packages.  “The above quoted prices are just an estimate.  We are happy to provide a free custom quote designed for your specific project needs and budget.”  

—————Add back in the "Individual Pricing" that we had on there earlier————————

6.  Below this put “please contact us for a free custom quote or general questions”  Make the “contact us” a link to send me an email

Front Page

1.  The more I look at the background picture of the mountain and the clouds, the less I like it.  Seems very boring and not completely sharp.  I’ve attached some photos that I think might look better but I’d like to make sure they are sharp and clear.  Like to have a Yosemite theme going.  Like to show half dome or the falls so keep them in the picture as much as possible.  (I don’t want to use a picture if it’s going to be a little blurry.)  (preference is Picture 3 then 2,4,5,6).  I'd like to replace both pictures on the front page with one of these. #1 might look good as the bottom picture. If these pictures don't work and you have something better, let me know.

Images added to google drive here: 
https://drive.google.com/drive/folders/0B7-L_YWYH3_YWkdwU0tBV0h4Y2c

due:
10-21-15    3p

**Comment by rodneystrong** [comment]
If the resolution isn't high enough from those photos, try and find a similar image from depositphotos.com 
and post the link to that image here and download it to our google drive as well.

**Comment by vanderbeam** [comment]
I'm not done updating this but the site is experiencing an internal server error. I'm giving you an update while it works itself out. 

When I updated the prices last time, making the commercial license smaller was actually something I had already attempted to do (it just felt right). I tried a few more things than I had attempted last time, but nothing is working. I've attached a screen shot of an alternative idea I had which is adjusting the box size a bit more and adding it into the description. 
![pricing example](https://cloud.githubusercontent.com/assets/12962001/10626071/4c16bc9a-7760-11e5-81e6-7f77f743b8c9.png)
(Left) Price in description; (Right) The size reduction made to the boxes w/o description (I actually also made the title ("Basic"/"Advanced") boxes about 10px smaller, also; that is not depicted in these pictures.)


I can swap out the picture again, for sure, but he wants the pictures to be sharp but keeps sending photos in small dimensions. The only Yosemite photos that will retain their resolution are Yosemite 02 and Yosemite 04. I'd love to use 01 or 03 because they're quite pretty but enlarging them to the needed dimensions will absolutely degrade the quality. See an example below:
![cenpaclogo-white](https://cloud.githubusercontent.com/assets/12962001/10626336/bb2133a2-7762-11e5-9d04-70292c9be17f.png)
See the pixelation? It makes the photo look like a textbook cover. 
Here's an example of 02:
![cenpaclogo-white](https://cloud.githubusercontent.com/assets/12962001/10626473/44ed349a-7764-11e5-81d2-b0cee212e074.png)

(I plan on retweaking the cenpac logo itself when we've decided on a picture)

I can use that same picture for both the top and bottom.... so much is cut off it probably wouldn't be very noticeable. My concern is I think using 04 or 05 will bring up his same concerns of being too "boring" and while the foliage in 06 makes the photo pop a bit more and it's large, it's not a very good quality, either (see below). I'm a little concerned the vivid colours in the pictures might clash with the site's colour scheme, but since I can test it out until the server works itself out, I'll cross that bridge when I get to it. 

![2](https://cloud.githubusercontent.com/assets/12962001/10626543/fbeecce4-7764-11e5-84a5-59d8be0c5189.png)

I guess... tl;dr: If he could send 01 and 03 in HD/larger size, I think he'd be a lot happier with the result.

**Comment by vanderbeam** [comment]
Ahhhh I missed that comment you put about the resolution. I'm looking on depositphotos now.

**Comment by rodneystrong** [comment]
I think this is the last thing that's remaining before I email the client. If possible, please get new images off of deposit photos and uploaded to the site before 4p today

**Comment by vanderbeam** [comment]
@rodneystrong Do you want me to replace the top or bottom photo? I put his photo (Y 02) in there for both.
I love this desertie photo. The sky is breattaking:
http://depositphotos.com/9744901/stock-photo-aerial-photography-the-himalayan-hengduan.html

Fluffy clouds:
http://depositphotos.com/81154442/stock-photo-blue-sky-with-white-clouds.html

Pretty sunset:
http://depositphotos.com/41676331/stock-photo-himalayan-mountains.html

Yosemite:
http://depositphotos.com/16996461/stock-photo-yosemite-national-park.html
http://depositphotos.com/14153468/stock-photo-yosemite-national-park.html
http://depositphotos.com/2160713/stock-photo-el-capitan-view-in-yosemite.html
http://depositphotos.com/3892426/stock-photo-high-sierra-stream.html
http://depositphotos.com/33390971/stock-photo-yosemite-usa.html
I really like this one: http://depositphotos.com/9794204/stock-photo-tunnel-view-yosemite.html
(There's a surprising lack of aerial stock photos of Yosemite)
This one too: http://depositphotos.com/8165913/stock-photo-panoramic-shot-of-tunnel-view.html

Let me know if any of these pique your fancy

**Comment by rodneystrong** [comment]
wait wait wait.. just got off the phone with him. he LOVES the photo you have on there right now, specifically the contrast in colors from the green trees, the red mountainside, and blue skies. 
can you find that exact same photo somewhere on depositphotos but in ridiculously sharp, high-res? 
and then crop and use that photo? i saw how you had to custom make that with the logo in there.

**Comment by vanderbeam** [comment]
@rodneystrong AH! OK, I'll look. I thought this was a photo he took. Checking now.

**Comment by vanderbeam** [comment]
@rodneystrong So I reverse image searched this photo.
Here is what appears to be the original poster: https://500px.com/photo/50304184/super-moon-over-yosemite-falls-by-william-mcintosh 
I'm saying that because there is a licensing fee. 
However, I don't think that applies to the picture we're using because the one we're using is that photo but someone has photoshopped it enough and it's on most popular wallpaper sites. Basically the resolution we have is the best that's out there.

**Comment by rodneystrong** [comment]
Ok, so the exact photo isn't available on the site we use. 

Try to find one that exists on deposit photos that looks similar and post links here

**Comment by vanderbeam** [comment]
So my mental association with these photos is "vivid." 

http://depositphotos.com/44491703/stock-photo-sunset-from-glacier-point.html
http://depositphotos.com/5978976/stock-photo-view-of-el-capitan-in.html
http://depositphotos.com/35704491/stock-photo-yosemite-merced-river-el-capitan.html
http://depositphotos.com/35703631/stock-photo-yosemite-merced-river-el-capitan.html 
http://depositphotos.com/35704813/stock-photo-yosemite-merced-river-el-capitan.html
http://depositphotos.com/24496657/stock-photo-horsetail-falls-lit-up-during.html?qview=24496657
http://depositphotos.com/26712739/stock-photo-yosemite-valley-sunset.html (Could probably photoshop this one and bring up the contrast)
http://depositphotos.com/28666765/stock-photo-cathedral-lake-with-cathedral-peak.html
http://depositphotos.com/35707095/stock-photo-yosemite-merced-river-el-capitan.html
http://depositphotos.com/31798577/stock-photo-yosemite-national-park-sierra-nevada.html

Let me know if any of those work for you.

**Comment by rodneystrong** [comment]
Nice effort, unfortunately none of those work ..  
The red, blue, and green colors from the photo really made an impression on him and I want that same effect in the new photo. 
I'll make a quick vid to explain exact requirements.

**Comment by rodneystrong** [comment]
http://somup.com/co630rFHO

**Comment by vanderbeam** [comment]
Throwing this one at you real quick 
![2](https://cloud.githubusercontent.com/assets/12962001/10681136/07d8eef0-78db-11e5-8111-fe93c2468390.jpg)

**Comment by vanderbeam** [comment]
@rodneystrong 
Some examples
![2](https://cloud.githubusercontent.com/assets/12962001/10681449/34158598-78de-11e5-81ab-29b05ed2a49c.png)
![3](https://cloud.githubusercontent.com/assets/12962001/10681448/34136682-78de-11e5-8c62-51ccf77d4563.png)
![4](https://cloud.githubusercontent.com/assets/12962001/10681451/34171b24-78de-11e5-9bba-90d4860cbcd6.png)
![1](https://cloud.githubusercontent.com/assets/12962001/10681450/3416b01c-78de-11e5-89d5-a18802ccaa06.png)

**Comment by vanderbeam** [comment]
This is what the image looks like that I upload into the Customizer. The top inch or so is covered by the Nav bar which is why there's that space above the logo. It's really long so it's still complete in 1920x1080. On a 13666 x 768 is cuts down about 1/6 on either side.

**Comment by rodneystrong** [comment]
Ok, the second one from the top looks like the best match. Good find. Buy it with our account and use it.

**Comment by vanderbeam** [comment]
This one right? 

![3](https://cloud.githubusercontent.com/assets/12962001/10684548/75581848-7903-11e5-9de7-e5251bd2ff47.png)

**Comment by rodneystrong** [comment]
Yes

**Comment by vanderbeam** [comment]
http://cenpac.editllc.com/ Lemme know wutcha think. Check Contact Us too

**Comment by rodneystrong** [comment]
Excellent work lady! thanks for handling this
