### ISSUE TITLE
Last adjustments hopefully

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#23]
http://somup.com/co630TFHt

due:
10-22-15     8p

**Comment by vanderbeam** [comment]
@rodneystrong These are done. Let me know if you like what I did with the Services. Usually to break up text I would use a newspaper layout but there just isn't enough content to do that so I created mini galleries. 
http://cenpac.editllc.com/

About the image in the background in the bottom, I'm honestly not sure. It's a widely distributed wallpaper. I don't know who made the edits to the original photo but from what I understand about photography copyright law is if someone makes a certain amount (I think a photographer once told me the magic number was three) of changes to a photo it doesn't count as the same photo anymore, which is why it's been able to be freely distributed. I went through a reasonable amount of wallpaper website that distribute this photo and there are no notes about licensing. Let me know what you want me to do.

**Comment by rodneystrong** [comment]
Good job with the services and the image galleries. 
Can you make them all the same layout? Real estate has the image gallery on the right, Industrial has them below the text, events and sports has them on the right. 
What's the reason you made Industrial have the gallery below the content? I'm open to leaving it as is but I just wanted to hear your reason first. 

For the bottom image on the home page, go to your wallpaper websites and post the link here that you got it from. Also, please upload these images to the google drive if you haven't already.

**Comment by vanderbeam** [comment]
@rodneystrong I did that because I felt that it was already repetitive enough that I was using the same photos in the gallery, I didn't like the idea that all of them would have the same layout as each other. in addition, each service has significantly varied amount of information and having picture to the right of the very small amount of text that was on the industrial, the images would be much bulkier. In my head having them line the bottom of the text weighed out the page more. 

And that picture is Yosemite 02. I used it from the image you sent me. 
Here's the full page of reverse google seach results: https://www.google.com/search?hl=en&q=yosemite+park&tbm=isch&tbs=simg:CAQSjAEaiQELEKjU2AQaAggBDAsQsIynCBpiCmAIAxIo-BX5FY0e6RX5FvsVhQzqFYse9BWkKsc4yDjnKNQooSqlKsk40yisNxowhWSr_1tD0B6ofHc_1eUYJzwQWc5dm8D-JUW2ZrSA_1huL23Q0dL4A6YAt7YNnACjbBEIAIMCxCOrv4IGgoKCAgBEgSb5OkeDA&sa=X&ved=0CBoQwg4oAGoVChMImPj2zbLXyAIVCuljCh3kIAQ0&biw=1920&bih=965#imgrc=_

**Comment by rodneystrong** [comment]
Wait I sent you that image?! Which means the client sent it to us!? 
-____-)  I'm gonna have to verify if he has a license to use it commercially.. *sigh 
Thanks for clarifying Meg. 

Just do the same thing with the new image I told you to use; crop a different section to use for the bottom.

**Comment by rodneystrong** [comment]
Ok, leave the Industrial page the way it is then and I'll ask if the client prefers it.
