### ISSUE TITLE
Cross Browser issue found

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#27]
OS: El Capitan
Browser: Safari 9.0

Go to cenpacimages.com and click on "Our Services" and then click on the "Real Estate" icon. This is what the client sees: 

![screen shot 2015-10-27 at 11 40 57 am](https://cloud.githubusercontent.com/assets/539962/10773903/5b6bdd32-7cbb-11e5-8e1a-ed67603332ab.png)

That big space should not be there. Please test this on your Mac using the browser noted above. 

If you find the issue, please fix it. 

due:
10-28-15    11a

**Comment by AaronAguilar** [comment]
Isn't this made in wordpress? I don't have the credentials

**Comment by rodneystrong** [comment]
yes, made in WP. I'll share credentials but you don't need credentials to initially trouble-shoot this issue. 

Open up your safari browser please and see if you get the same result as the screenshot

**Comment by AaronAguilar** [comment]
Yeah, I do see the same result. I check the other pages and it seems to be doing it for the events as well. 
<img width="1265" alt="screen shot 2015-10-27 at 3 09 05 pm" src="https://cloud.githubusercontent.com/assets/10875354/10774157/d3d462ac-7cbc-11e5-8cb3-f78cd3d09541.png">
<img width="1264" alt="screen shot 2015-10-27 at 3 09 37 pm" src="https://cloud.githubusercontent.com/assets/10875354/10774158/d3d538b2-7cbc-11e5-8083-f253514d1e9a.png">

**Comment by rodneystrong** [comment]
hooooly crap. ok you know what to do. use the inspector and find out what CSS is screwing that up.

**Comment by AaronAguilar** [comment]
Updated -  for some reason the table moved it when the width was 50%, which is why only two services did it and not the third. Anyways, I added a negative margin that only happens in Safari. 

<img width="1202" alt="screen shot 2015-10-27 at 6 41 44 pm" src="https://cloud.githubusercontent.com/assets/10875354/10777665/fa92b45c-7cda-11e5-86ca-5dea0c80fa69.png">
<img width="1213" alt="screen shot 2015-10-27 at 6 42 01 pm" src="https://cloud.githubusercontent.com/assets/10875354/10777666/fa9669d0-7cda-11e5-8716-57ae93547a26.png">

**Comment by rodneystrong** [comment]
YOU are the SHIT aaron. Good job on figuring this out.
